name: Setup Sample Repository
on:
  workflow_dispatch:
    inputs:
      TARGET_REPO:
        description: 'The repository to clone to'
        required: true
      PROJECT_NAME:
        description: "Name of the project"
        required: true
      REGION:
        description: "Region for the sub account"
        required: true
      COST_CENTER:
        description: "Cost center for the project"
        required: true
      STAGE:
        description: "Stage for the project"
        required: true
      ORGANIZATION:
        description: "Organization for the project"
        required: true  

permissions:
  contents: write
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: btp-automation-scenarios/sample-btptf-setup
          path: source
          sparse-checkout: |
            .
            .github
            .devcontainer
            infra
            src
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: btp-automation-scenarios/${{ github.event.inputs.TARGET_REPO }}
          path: target
          token:  ${{ secrets.GH_CLONE_TOKEN }}
      - name: Copy files from source to target
        shell: bash
        run: |
          cp -rf source/* target/
          cp -rf source/.devcontainer target/
          cp -rf source/.github target/
          cp -rf source/.gitignore target/
          cd target
          git config user.name "btp-automation-scenarios"
          git config user.email "noreply@btpautomation.com"
          git add .
          git commit -m "Basic setup by GH Action"
          git push
  
  trigger-terraform:
    runs-on: ubuntu-latest
    needs:  clone-repo
    steps:
      - uses: actions/script@v7
        env:
          PROJECT_NAME: ${{ github.event.inputs.PROJECT_NAME }}
          REGION: ${{ github.event.inputs.REGION }}
          COST_CENTER: ${{ github.event.inputs.COST_CENTER }}
          STAGE: ${{ github.event.inputs.STAGE }}
          ORGANIZATION: ${{ github.event.inputs.ORGANIZATION }}
          TARGET_REPO: ${{ github.event.inputs.TARGET_REPO }}
        with:
          github-token: ${{ secrets.GH_CLONE_TOKEN }}
          script: |
            const result = await github.request(
              'POST /repos/{owner}/{repo}/dispatches',
              {
                owner: 'btp-automation-scenarios',
                repo: process.env.TARGET_REPO,
                event_type: 'triggerTerraformSetup',
                client_payload: {
                  PROJECT_NAME: process.env.PROJECT_NAME,
                  REGION: process.env.REGION,
                  COST_CENTER: process.env.COST_CENTER,
                  STAGE: process.env.STAGE,
                  ORGANIZATION: process.env.ORGANIZATION
                }
              }
            )
            console.log(result)
            
